/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface StartPaymentDTO {
  'customer-id'?: string;
  amount?: number;
  currency?: string;
}

export interface TransactionTokenDTO {
  token?: string;
}

export interface PaymentStatusDTO {
  status?: string;
}

/**
 * Save the JSON about the specs of the config of the UI element
 * @summary Save JSON to render the UI
 */
export type createStyleResponse200 = {
  data: string
  status: 200
}
    
export type createStyleResponseSuccess = (createStyleResponse200) & {
  headers: Headers;
};
;

export type createStyleResponse = (createStyleResponseSuccess)

export const getCreateStyleUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/style`
}

export const createStyle = async (createStyleBody: string, options?: RequestInit): Promise<createStyleResponse> => {
  
  const res = await fetch(getCreateStyleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStyleBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createStyleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createStyleResponse
}



/**
 * Initiates a new payment process and return the token of the transaction
 * @summary Start a payment
 */
export type startPaymentResponse200 = {
  data: TransactionTokenDTO
  status: 200
}
    
export type startPaymentResponseSuccess = (startPaymentResponse200) & {
  headers: Headers;
};
;

export type startPaymentResponse = (startPaymentResponseSuccess)

export const getStartPaymentUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/start`
}

export const startPayment = async (startPaymentDTO: StartPaymentDTO, options?: RequestInit): Promise<startPaymentResponse> => {
  
  const res = await fetch(getStartPaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startPaymentDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: startPaymentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startPaymentResponse
}



/**
 * Retrieves the styling configuration for the payment interface
 * @summary Get payment style
 */
export type getStyleResponse200 = {
  data: string
  status: 200
}
    
export type getStyleResponseSuccess = (getStyleResponse200) & {
  headers: Headers;
};
;

export type getStyleResponse = (getStyleResponseSuccess)

export const getGetStyleUrl = (publicKey: string,) => {


  

  return `http://52.15.192.69:8080/api/payments/style/${publicKey}`
}

export const getStyle = async (publicKey: string, options?: RequestInit): Promise<getStyleResponse> => {
  
  const res = await fetch(getGetStyleUrl(publicKey),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStyleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStyleResponse
}



/**
 * Retrieves the current status of a payment
 * @summary Check payment status
 */
export type checkStatusResponse200 = {
  data: PaymentStatusDTO
  status: 200
}
    
export type checkStatusResponseSuccess = (checkStatusResponse200) & {
  headers: Headers;
};
;

export type checkStatusResponse = (checkStatusResponseSuccess)

export const getCheckStatusUrl = (paymentId: string,) => {


  

  return `http://52.15.192.69:8080/api/payments/status/${paymentId}`
}

export const checkStatus = async (paymentId: string, options?: RequestInit): Promise<checkStatusResponse> => {
  
  const res = await fetch(getCheckStatusUrl(paymentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkStatusResponse
}

/**
 * Render the payment form with the style configuration
 * @summary Render payment form
 */
export interface YunoSDK {
  render: (containerId: string, publicKey: string) => Promise<void>;
}

export const Yuno: YunoSDK = {
  render: async (containerId: string, publicKey: string) => {
    try {
      const response = await getStyle(publicKey);
      const formFields = response.data;
      
      const container = document.getElementById(containerId);
      if (!container) {
        throw new Error(`Container with id "${containerId}" not found`);
      }
      
      // This will be implemented by the integrator using React
      // For now, we just store the data in a data attribute
      container.setAttribute('data-form-fields', JSON.stringify(formFields));
      container.setAttribute('data-public-key', publicKey);
      
      // Dispatch a custom event that the React app can listen to
      const event = new CustomEvent('yunoFormReady', {
        detail: { formFields, publicKey }
      });
      window.dispatchEvent(event);
    } catch (error) {
      console.error('Error rendering Yuno form:', error);
      throw error;
    }
  }
};
