/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface StartPaymentRequest {
  amount?: number;
  currency?: string;
  customerId?: string;
}

export interface StartPaymentResponse {
  paymentId?: string;
  status?: string;
  redirectUrl?: string;
}

export interface ContinuePaymentRequest {
  paymentId?: string;
  paymentMethodToken?: string;
}

export interface PaymentStatusResponse {
  paymentId?: string;
  status?: string;
  lastUpdated?: string;
}

export type SaveStyle200 = {[key: string]: { [key: string]: unknown }};

/**
 * Returns a list of all registered users
 * @summary Get all users
 */
export type getAllUsersResponse200 = {
  data: string
  status: 200
}
    
export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
;

export type getAllUsersResponse = (getAllUsersResponseSuccess)

export const getGetAllUsersUrl = () => {


  

  return `http://52.15.192.69:8080/api/users`
}

export const getAllUsers = async ( options?: RequestInit): Promise<getAllUsersResponse> => {
  
  const res = await fetch(getGetAllUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllUsersResponse
}



/**
 * Adds a new user to the list
 * @summary Create a new user
 */
export type createUserResponse200 = {
  data: string
  status: 200
}
    
export type createUserResponseSuccess = (createUserResponse200) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = () => {


  

  return `http://52.15.192.69:8080/api/users`
}

export const createUser = async (createUserBody: string, options?: RequestInit): Promise<createUserResponse> => {
  
  const res = await fetch(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserResponse
}



/**
 * Retrieves the styling configuration for the payment interface
 * @summary Get payment style
 */
export type getStyleResponse200 = {
  data: string
  status: 200
}
    
export type getStyleResponseSuccess = (getStyleResponse200) & {
  headers: Headers;
};
;

export type getStyleResponse = (getStyleResponseSuccess)

export const getGetStyleUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/style`
}

export const getStyle = async ( options?: RequestInit): Promise<getStyleResponse> => {
  
  const res = await fetch(getGetStyleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStyleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStyleResponse
}



/**
 * Saves the styling configuration for the payment interface
 * @summary Save payment style
 */
export type saveStyleResponse200 = {
  data: SaveStyle200
  status: 200
}
    
export type saveStyleResponseSuccess = (saveStyleResponse200) & {
  headers: Headers;
};
;

export type saveStyleResponse = (saveStyleResponseSuccess)

export const getSaveStyleUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/style`
}

export const saveStyle = async (saveStyleBody: string, options?: RequestInit): Promise<saveStyleResponse> => {
  
  const res = await fetch(getSaveStyleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveStyleBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: saveStyleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveStyleResponse
}



/**
 * Initiates a new payment process
 * @summary Start a payment
 */
export type startPaymentResponse200 = {
  data: StartPaymentResponse
  status: 200
}
    
export type startPaymentResponseSuccess = (startPaymentResponse200) & {
  headers: Headers;
};
;

export type startPaymentResponse = (startPaymentResponseSuccess)

export const getStartPaymentUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/start`
}

export const startPayment = async (startPaymentRequest: StartPaymentRequest, options?: RequestInit): Promise<startPaymentResponse> => {
  
  const res = await fetch(getStartPaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startPaymentRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: startPaymentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startPaymentResponse
}



/**
 * Continues an existing payment with a method token
 * @summary Continue a payment
 */
export type continuePaymentResponse200 = {
  data: PaymentStatusResponse
  status: 200
}
    
export type continuePaymentResponseSuccess = (continuePaymentResponse200) & {
  headers: Headers;
};
;

export type continuePaymentResponse = (continuePaymentResponseSuccess)

export const getContinuePaymentUrl = () => {


  

  return `http://52.15.192.69:8080/api/payments/continue`
}

export const continuePayment = async (continuePaymentRequest: ContinuePaymentRequest, options?: RequestInit): Promise<continuePaymentResponse> => {
  
  const res = await fetch(getContinuePaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      continuePaymentRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: continuePaymentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as continuePaymentResponse
}



/**
 * Returns a single user
 * @summary Get a user by name
 */
export type getUserResponse200 = {
  data: string
  status: 200
}
    
export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = (name: string,) => {


  

  return `http://52.15.192.69:8080/api/users/${name}`
}

export const getUser = async (name: string, options?: RequestInit): Promise<getUserResponse> => {
  
  const res = await fetch(getGetUserUrl(name),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}



/**
 * Retrieves the current status of a payment
 * @summary Check payment status
 */
export type checkStatusResponse200 = {
  data: PaymentStatusResponse
  status: 200
}
    
export type checkStatusResponseSuccess = (checkStatusResponse200) & {
  headers: Headers;
};
;

export type checkStatusResponse = (checkStatusResponseSuccess)

export const getCheckStatusUrl = (paymentId: string,) => {


  

  return `http://52.15.192.69:8080/api/payments/status/${paymentId}`
}

export const checkStatus = async (paymentId: string, options?: RequestInit): Promise<checkStatusResponse> => {
  
  const res = await fetch(getCheckStatusUrl(paymentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkStatusResponse
}
